apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: habit-tracker
  namespace: app
spec:
  ingressClassName: nginx
  rules:
    - host: habit.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: habit-tracker
                port:
                  number: 80
