apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: default
spec:
  encryptedData:
    password: AgA1u6oH9jmwNk18RicqyecmJbffXN9zQNeVwo/q/mh2m+q1PSUrElRAdPQlhXwpSQJjscoSBL1Fwnns6zCVl2RcZTAEEvHNeZALjYgKW6hCUFAbTu74vzl+dVBUQGUAmrq7Gk8NmBZwUYjBL0u4N7+spPthVvIJBOelwGbanW4PObeSU/pfdxn45FXZpOYYGSQgjvhQmB8PAnbvjDOY7SJvyheSL9O91PO7Id9fVhXLun+3UQ9u5ads0oT1ErTiIClEPkjrtMscPdQo5R3LRKdGxEd+Kr1bVvE03DGqEhqwVXOwY+FKdBqnz3Ieoo0YVi/OGFZTVtblTTJKYlSyQrm/j0IKR9dZu3YL+lu4klx9GTORvfguMgHZPJwNwFgXtmXt75vzUIkTIOOTHPipkDgFSRAob0MZQeVPvXSYFBtL7EhFCiJjDROtRfE9vPITsXU3qr/4cvU7myzyhIGB/2+ll55+HWqRM8EgYqk3VnY+9upaU738l9MyTNbIt543cU5wPte1HYfEB9Ngv8F9kqbtg6hhyk+19odoAS/PTZ/v8BZ1VJVUUECiBNZVzfuqueJa+tGa5GdYSJ3ObD0FmzKI6LQq3iL0SkK5HVH65WGSend9v56wYG9WyaEnby0Asuqkvr8QCdiLsfMKT54QvTJYRzlYN2Xupvi8Xd1hqEgw2pZTi1vqdPgW3F1DUFtBWqzmcrSISuXI9+7FLR7ECMi7x0l8
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: default
