apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: app
spec:
  encryptedData:
    password: AgBgPKDvNzDyxw9KlmRoFF5j4lBcYjybupHn3EIuJDSNpTS7DCH3hPMTivws1aCvRx/qJ6PT36qRJauPtwu7uZeG1BV+CSP9sj2CSxPlmzA8BxAddI8Iip2e/FtywQzUQiBFZpHcZtJ50ozZ2tfuHDnibErbO3Syl5cNcVJy109kOHQyYPWCDXEQSNpE/p4QxtE0/CeeVmHhOKDHUdCmbKWBD7ay53Nz+1eohseO2F3UtcfcB6+fpSq+SAMBzm+JE8D/q4/UdQPX1bCkS4cPwWkYQudcoG7+RVFkwVdMBcLsKNB8EEg4pfBTrIa3lBu2OhU67DYIjNTSz0782TwdWUdTUrNFi5924JWDsWn4GJs31lbLdLj3N6d1NvrKENc+24o0HbCg0vpgqI6QRekUX5A+LLhDXC8gCQS2W28obms9VL1m49ObJ4UFIY8+6kIZW4nOyXYJj9fNFr4bqNAvP+odzGfenDF4S4xKrhFH9wBj6LTaPEZzWepGN0EJQiel1cTFQzhMysBiYZwl0gmqqqG0RWie3yymW9Fg5kJ/fcJsBd3WiHAhZ38cStayeVAAuFSV8amtts2r/UZwfiKck2Yqz2oucWrvRo241tk2+tJn3LeSq0wqyWiGflnG/w1U0Dtlr1nA5R7ubTNjKDu42NzqTlRhl0VXvYJ00CQgvCxiluXpUDA8iSK4WUE0CkBZGeF8WQ+cCw/eu7OMYINmL6sUzkz0
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: app
